### ISSUE TITLE
eid和fp获取问题

### ISSUE THREAD

**Issue by DreamSaddle** [ChinaVolvocars/jd_maotai_seckill#40]
通过 `README` 中的 `_JdTdudfp ` 如果获取出来是个空对象。则可以通过下面两个变量获取
`_JdEid` 获取eid, `_JdJrTdRiskFpInfo` 获取fp

**Comment by waterwaterrr** [comment]
> 通过 `README` 中的 `_JdTdudfp ` 如果获取出来是个空对象。则可以通过下面两个变量获取
> `_JdEid` 获取eid, `_JdJrTdRiskFpInfo` 获取fp

你没有点击提交订单

**Comment by wuxiaowu798** [comment]
如你们所说，但是我并没有看到控制台输出_JdTdudfp，_JdEid，_JdJrTdRiskFpInfo，我也点击了提交订单

**Comment by LeeHubery** [comment]
控制台输出空 +1

**Comment by wuxiaowu798** [comment]
估计是狗东做了策略

**Comment by DreamSaddle** [comment]
按我说的那个方式不需要提交也可以通过 `_JdEid `和 `_JdJrTdRiskFpInfo `获取到的。

**Comment by wuxiaowu798** [comment]
> 按我说的那个方式不需要提交也可以通过 `_JdEid `和 `_JdJrTdRiskFpInfo `获取到的。

你有截图么？我再mac和windows上都没有打印出来
